version: "3.8"
services:
  online-shop:
    image: test-nextjs-jenkins
    container_name: test-nextjs-jenkins-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
